### ISSUE TITLE
Hidden `#[doku(` in docs.rs example snippet

### ISSUE THREAD

**Issue by dbr** [anixe/doku#15]
Minor thing but the example on
https://docs.rs/doku/0.10.1/doku/
does not include the lines like `#[doku(example = "localhost")]` which made the example quite hard to understand! They appear correctly in the README on Github

**Comment by Patryk27** [comment]
Hi, thanks for reporting; I've just released 0.10.2 with improved docs (might take a while for docs.rs to catch up though) - please let me know if the wording is better now 🙂

**Comment by Patryk27** [comment]
I'm gonna go ahead and assume that this issue has been resolved - thanks for reporting! 🙂
